In [0]:
import numpy as np

npa  = np.array([1,2,3,4,5])
print(npa)
print(type(npa))

npar = np.arange(10)
print(npar)
type(npar)


npa
npar

[1 2 3 4 5]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
print(npa.ndim)
print(npar.ndim)
print(len(npa))
print(npa.shape)

1
1
5
(5,)


In [0]:
#python list versus python array - timing it to see how fast np arrays are

L = range(100)
%timeit [i**2 for i in L]

10000 loops, best of 3: 27.4 µs per loop


In [0]:
npr = np.arange(100)
%timeit npr **2

The slowest run took 45.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 910 ns per loop


In [0]:
npd = np.array([[1,2,3], [4,5,6]])
print(npd)
print(npd.ndim)
print(npd.shape)
print(len(npd))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2


In [0]:
d3 = np.array([  [   [0,1], [2,3]   ], [   [4,5], [6,7] ]      ])
print(d3)
print(d3.shape)
print(d3.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
3


In [0]:
d222 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
d33.shape
#d33.ndim

(2, 2, 2)

In [0]:
# to create 2x3x5 3d matrix

d235 = np.array([   
    [
        [1,2,3,4,5],
        [5,6,7,8,9],
        [10,1,2,3,4]   
    ],
    [
        [1,2,3,4,5],
        [5,6,7,8,9],
        [10,1,2,3,4]
    ] 
])

d235.shape






#a = np.zeros((2,3,5))
#a


(2, 3, 5)

In [0]:
import numpy as np
d335 = np.array ([
    [
        [1,2,3,4,5],
        [5,6,7,8,9],
        [10,1,2,3,4] 
    ],
    [
        [1,2,3,4,5],
        [5,6,7,8,9],
        [10,1,2,3,4] 
    ],
    [
        [1,2,3,4,5],
        [5,6,7,8,9],
        [10,1,2,3,4] 
    ]
])

d335.shape





(3, 3, 5)

In [0]:
d121 = np.array ([
  [
      [1],
      [4]  
  ]  
])

d121.shape

(1, 2, 1)

In [0]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a1 = np.arange(1,10,2)
a1

array([1, 3, 5, 7, 9])

In [0]:
a = np.linspace(0,1,6)
a


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [0]:
a = np.zeros((3,3))
print(a)
b = np.ones((3,3))
b.ndim

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2

In [0]:
eye = np.eye(3)
eye
eye.ndim

2

In [0]:
eye2 = np.eye(2,3)
eye2
#eye2.shape
eye2.ndim

2

In [0]:
a = np.diag([1,2,3,4])
a
a.shape
a = np.diag(a)
a

array([1, 2, 3, 4])

In [0]:
a = np.random.rand(5)
a
#a.shape
#a.ndim

1

In [0]:
a = np.random.randn(4)
a

array([0.67385522, 0.25835991, 0.04434028, 0.77245607])

In [0]:
#numpy dtype

a = np.arange(4, dtype='int') #'float64'
a

array([0, 1, 2, 3])

In [0]:
a = np.array([1+2j, 2+3j])
a.dtype

dtype('complex128')

In [0]:
b = np.array(['True', 'False', 'True', 'False'])
print(b.dtype)

<U5


In [0]:
s = np.array(['Ra', 'Re'])
s.dtype

dtype('<U2')

In [0]:
a = np.arange(10)
a[5]

5

In [0]:
a = np.diag([4,3,2,1])
a

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [0]:
print(a[2,3])

0


In [0]:
a[2,3] = 5
a

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 5],
       [0, 0, 0, 1]])

In [0]:
#slicing

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:9:2]

array([1, 3, 5, 7])

In [0]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [0]:
print(a) 

[ 0  1  2  3  4 10 10 10 10 10]


In [0]:
a = np.arange(10)
b = np.arange(5)

print(a)
print(b)

a[5:] = b[: : -1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 1 2 3 4 4 3 2 1 0]


In [0]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)
np.shares_memory(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


True

In [0]:
#force copy
a = np.arange(10)
b = a[::2].copy()
a[1] = 10
print(a)
print(b)

[ 0 10  2  3  4  5  6  7  8  9]
[0 2 4 6 8]


In [0]:
#mask
ra = np.random.randint(0,20,15)
ra

array([ 7, 16, 17, 19, 14, 11, 11,  4,  2,  6,  9, 15, 10, 15, 15])

In [0]:
mask =  (ra % 2 == 0)
extract = ra[mask]
extract

array([16, 14,  4,  2,  6, 10])

In [0]:
#numpy operations

a = np.arange(5)
print(a)

a= a+1
print(a)

a = a**2
print(a)

[0 1 2 3 4]
[1 2 3 4 5]
[ 1  4  9 16 25]


In [0]:
a = np.arange(4)
print(a)
b = np.ones(4)
print(b)

print(a - b)
print(a * b)

[0 1 2 3]
[1. 1. 1. 1.]
[-1.  0.  1.  2.]
[0. 1. 2. 3.]


In [0]:
di = np.diag([1,2,3,4])
print(di)

print(di * di)

print (d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [0]:
import numpy as np

di = np.diag([1,2,3,4])
print(di.dot(di))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [0]:
#comparison operator
a = [1,2,3,4]
b = [1.4,5.2]

a == b

a1 = np.array([1,2,3,4])
a2 = np.array([2,1,3,4])

#a1 == a2

a1 > a2

array([False,  True, False, False])

In [0]:
e1 = np.array([1,2,3,4])
e2 = np.array([1,2,3,4])

print(np.array_equal(e1,e2))

True


In [0]:
a1 = np.array([1,0,0,0,1], dtype=bool)
a2 = np.array([0,0,0,0,1], dtype=bool)

print(np.logical_or(a1,a2))
print(np.logical_and(a1,a2))

[ True False False False  True]
[False False False False  True]


In [0]:
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
a3 = np.arange(4)
print(np.sum(a3))


6


In [0]:
ax = np.array([[1,1], [2,2]])
print(ax)

[[1 1]
 [2 2]]


In [0]:
ax.sum(axis=0) #col addition if axis=0


array([3, 3])

In [0]:
x = np.array([1,2,3])
x.min()
x.max()

3

In [0]:
import numpy as np
#np.all(['True', 'False'])
#np.any(['True', 'False'])

In [0]:
a = np.array([1,2,3,4])
b = np.ones(4)
print(a)
print(b)
#b = b ** 2
#print(b)
a -b 

[1 2 3 4]
[1. 1. 1. 1.]


array([0., 1., 2., 3.])

In [0]:
c = np.diag([1,2,3,4])
c
print(c * c) #similar to c.dot(c)
print("-=-=-=-=-")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
-=-=-=-=-
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [0]:
a = np.array([1,2,3,4])
b = np.array([1,2,4,5])
a == b
a >= b

np.array_equal(a,b)

False

In [0]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,1,0,0], dtype=bool)
print(np.logical_and(a,b))
print(np.logical_or(a,b))

[ True  True False False]
[ True  True False False]


In [0]:
print(np.sin(a))
print(np.exp(a))
print(np.log(a))


[0.8413 0.8413 0.     0.    ]
[2.719 2.719 1.    1.   ]
[  0.   0. -inf -inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
x = np.array([[1,2], [2,3]])
print(sum(x))
print(x.sum (axis=1)) #row addition

[3 5]
[3 5]


In [0]:
x = np.array([6,2,3,4])
x.min()
x.max()
x.argmin()
x.argmax()

0

In [0]:
a = np.zeros([50,50])
a.shape
np.any(a != 0)
a.dtype
np.all(a == a)

#b = np.zeros((50,50))  
#b.shape
#b.ndmin   -> not working
#np.any(a !=0)


True

In [0]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all()

True

In [0]:
x = np.array([1,2,3,1])
x.mean()
np.median(x)

1.5

In [0]:
#upload poplulation data

data = np.loadtxt('populations.txt')
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [0]:
#data.T
year, hare, lynex, carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [0]:
popl = data[:, 1:]
popl
#standard deviation
popl.std(axis=0)

#species having hightest popl each year
species = np.argmax(popl, axis=1)
print(species)

[2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2]


In [0]:
a = np.tile(np.arange(0,40,10), (3,1))
print(a)
a.T

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [0]:
b = np.array([0,1,2])
b

b.shape #(3,)
a.shape

a.T + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [0]:
a = np.array([[0,10,20,30]])
a.shape
print(a)
b = np.array([1,2,3])

a.T + b

[[ 0 10 20 30]]


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [0]:
#There is another way of doing this

a = np.arange(0,40,10)
a.shape #(4,)
a.ndim #1D array
print(a) #[0,10,20,30]

a = a[:,np.newaxis] #add axis and becomes 2D array
a.shape #(4,1)
a.ndim #2D array
print(a)
print(a + b)

[ 0 10 20 30]
[[ 0]
 [10]
 [20]
 [30]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [0]:
#flattening

a = np.array([[1,2,3], [3,4,5]])
a.shape
a.ndim
a.ravel()

array([1, 2, 3, 3, 4, 5])

In [0]:
print(a.T)
print(a.T.ravel())

[[1 3]
 [2 4]
 [3 5]]
[1 3 2 4 3 5]


In [0]:
b = np.array([[2,3,5], [6,7,8]])
br = b.ravel()
print(br)
br.reshape((2,3))

[2 3 5 6 7 8]


array([[2, 3, 5],
       [6, 7, 8]])

In [0]:
#3D matrix and shuffling

a = np.arange(4*3*2)
a.shape
a = a.reshape((4,3,2))

In [0]:
print(a)
a[0,2,1] #0th matrix, 2nd row and 1st col

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


5

In [0]:
a = np.arange(4)
print(a)
a.resize((8))
print(a)

[0 1 2 3]
[0 1 2 3 0 0 0 0]


In [0]:
a = np.array([[5,1,7,], [6,1,4]])
b = np.sort(a, axis=1)
print(b)

[[1 5 7]
 [1 4 6]]


In [0]:
a.sort(axis=0)
print(a)

[[5 1 4]
 [6 1 7]]


In [0]:
a = np.array([1,3,4,2])
j = np.argsort(a) #sort the array and then show the indices

print(j)
print(a[j])

[0 3 1 2]
[1 2 3 4]
